# Generated by Django 3.0.3 on 2020-02-28 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptop', to='db.Product'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc', to='db.Product'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer', to='db.Product'),
        ),
    ]
